name: Release

on:
  push:
    tags:
      - v[0-9]+.*

jobs:
  create-release:
    if: github.repository_owner == '0xnu'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/create-gh-release-action@v1
        with:
          changelog: CHANGELOG.md
          branch: main
          token: ${{ secrets.OXNU_TOKEN }}

  create-package:
    needs: create-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20
      - name: Build package
        run: |
          go mod download
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o main ./cmd/main.go
      - name: Upload package to release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref }}
          files: main
          name: Package Release ${{ github.ref_name }}
          token: ${{ secrets.OXNU_TOKEN }}