name: Release

on:
  push:
    tags:
      - v[0-9]+.*

jobs:

  create-release:
    if: github.repository_owner == '0xnu'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/create-gh-release-action@v1
        with:
          changelog: CHANGELOG.md
          branch: main
          token: ${{ secrets.OXNU_TOKEN }}

  releases-matrix:
    name: Release Go Binary
    needs: create-release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-latest]
        goarch: [amd64]
    steps:
      - uses: actions/checkout@v2
      - name: Build Go Binary
        run: |
          go build -o main ./cmd/main.go
      - uses: wangyoucao577/go-release-action@v1.12
        with:
          github_token: ${{ secrets.OXNU_TOKEN }}
          goos: ${{ matrix.os == 'ubuntu-18.04' && 'linux' || 'darwin' }}
          goarch: ${{ matrix.goarch }}
          goversion: "https://golang.org/dl/go1.16.4.linux-amd64.tar.gz"
          ldflags: -w -s -X main.COMMIT=${{ github.sha }} -X main.GOVERSION=go1.16.4.linux-amd64
          extra_files: main
